const banqueQuestions = {
  italien: {
    A1: [
      { mot: "Buongiorno", traduction: "Bonjour" },
      { mot: "Arrivederci", traduction: "Au revoir" },
      { mot: "Grazie", traduction: "Merci" },
      { mot: "Per favore", traduction: "S'il vous plaît" },
      { mot: "Si", traduction: "Oui" },
      { mot: "No", traduction: "Non" },
      { mot: "Acqua", traduction: "Eau" },
      { mot: "Pane", traduction: "Pain" },
      { mot: "Mangiare", traduction: "Manger" },
      { mot: "Bere", traduction: "Boire" },
      { mot: "Dormire", traduction: "Dormir" },
      { mot: "Amico", traduction: "Ami" },
      { mot: "Famiglia", traduction: "Famille" },
      { mot: "Casa", traduction: "Maison" },
      { mot: "Libro", traduction: "Livre" },
      { mot: "Città", traduction: "Ville" },
      { mot: "Scuola", traduction: "École" },
      { mot: "Macchina", traduction: "Voiture" },
      { mot: "Tempo", traduction: "Temps" },
      { mot: "Sole", traduction: "Soleil" },
      { mot: "Luna", traduction: "Lune" },
      { mot: "Mare", traduction: "Mer" },
      { mot: "Montagna", traduction: "Montagne" },
      { mot: "Rosso", traduction: "Rouge" },
      { mot: "Blu", traduction: "Bleu" },
      { mot: "Verde", traduction: "Vert" },
      { mot: "Uno", traduction: "Un" },
      { mot: "Due", traduction: "Deux" },
      { mot: "Tre", traduction: "Trois" },
      { mot: "Ciao", traduction: "Salut" },
      { mot: "Prego", traduction: "De rien" }
    ],
    A2: [
      { mot: "Viaggio", traduction: "Voyage" },
      { mot: "Cucinare", traduction: "Cuisiner" },
      { mot: "Lavoro", traduction: "Travail" },
      { mot: "Salute", traduction: "Santé" },
      { mot: "Tempo libero", traduction: "Temps libre" },
      { mot: "Cercare", traduction: "Chercher" },
      { mot: "Trovare", traduction: "Trouver" },
      { mot: "Capire", traduction: "Comprendre" },
      { mot: "Pulire", traduction: "Nettoyer" },
      { mot: "Comprare", traduction: "Acheter" }
    ],
    B1: [
      { mot: "Esperienza", traduction: "Expérience" },
      { mot: "Opportunità", traduction: "Opportunité" },
      { mot: "Decisione", traduction: "Décision" },
      { mot: "Sviluppo", traduction: "Développement" },
      { mot: "Ambiente", traduction: "Environnement" },
      { mot: "Società", traduction: "Société" },
      { mot: "Confrontare", traduction: "Comparer" },
      { mot: "Spiegare", traduction: "Expliquer" },
      { mot: "Suggerire", traduction: "Suggérer" },
      { mot: "Risolvere", traduction: "Résoudre" }
    ],
    B2: [
      { mot: "Consapevolezza", traduction: "Conscience / Sensibilisation" },
      { mot: "Cambiamento", traduction: "Changement" },
      { mot: "Sfida", traduction: "Défi" },
      { mot: "Sostenibile", traduction: "Durable" },
      { mot: "Incoraggiare", traduction: "Encourager" },
      { mot: "Sottolineare", traduction: "Souligner" },
      { mot: "Approfondire", traduction: "Approfondir" },
      { mot: "Raggiungere", traduction: "Atteindre" },
      { mot: "Gestire", traduction: "Gérer" },
      { mot: "Evitare", traduction: "Éviter" }
    ],
    C1: [
      { mot: "Ineluttabile", traduction: "Inéluctable" },
      { mot: "Polemica", traduction: "Polémique" },
      { mot: "Paradigma", traduction: "Paradigme" },
      { mot: "Eterogeneo", traduction: "Hétérogène" },
      { mot: "Contraddistinguere", traduction: "Distinguer / Caractériser" },
      { mot: "Implementazione", traduction: "Mise en œuvre" },
      { mot: "Rivendicare", traduction: "Revendiquer" },
      { mot: "Auspicio", traduction: "Souhait" },
      { mot: "Delineare", traduction: "Esquisser / Tracer" },
      { mot: "Soffermarsi", traduction: "S'attarder" }
    ]
  },
  portugais: {
    A1: [
      { mot: "Olá", traduction: "Bonjour / Salut" },
      { mot: "Obrigado", traduction: "Merci" },
      { mot: "Por favor", traduction: "S'il vous plaît" },
      { mot: "Sim", traduction: "Oui" },
      { mot: "Não", traduction: "Non" },
      { mot: "Água", traduction: "Eau" },
      { mot: "Pão", traduction: "Pain" },
      { mot: "Comer", traduction: "Manger" },
      { mot: "Beber", traduction: "Boire" },
      { mot: "Dormir", traduction: "Dormir" },
      { mot: "Amigo", traduction: "Ami" },
      { mot: "Família", traduction: "Famille" },
      { mot: "Casa", traduction: "Maison" },
      { mot: "Livro", traduction: "Livre" },
      { mot: "Cidade", traduction: "Ville" },
      { mot: "Escola", traduction: "École" },
      { mot: "Carro", traduction: "Voiture" },
      { mot: "Tempo", traduction: "Temps" },
      { mot: "Sol", traduction: "Soleil" },
      { mot: "Lua", traduction: "Lune" },
      { mot: "Mar", traduction: "Mer" },
      { mot: "Montanha", traduction: "Montagne" },
      { mot: "Vermelho", traduction: "Rouge" },
      { mot: "Azul", traduction: "Bleu" },
      { mot: "Verde", traduction: "Vert" },
      { mot: "Um", traduction: "Un" },
      { mot: "Dois", traduction: "Deux" },
      { mot: "Três", traduction: "Trois" },
      { mot: "Tchau", traduction: "Au revoir" },
      { mot: "De nada", traduction: "De rien" }
    ],
    A2: [
      { mot: "Viagem", traduction: "Voyage" },
      { mot: "Cozinhar", traduction: "Cuisiner" },
      { mot: "Trabalho", traduction: "Travail" },
      { mot: "Saúde", traduction: "Santé" },
      { mot: "Tempo livre", traduction: "Temps libre" },
      { mot: "Procurar", traduction: "Chercher" },
      { mot: "Encontrar", traduction: "Trouver" },
      { mot: "Entender", traduction: "Comprendre" },
      { mot: "Limpar", traduction: "Nettoyer" },
      { mot: "Comprar", traduction: "Acheter" }
    ],
    B1: [
      { mot: "Experiência", traduction: "Expérience" },
      { mot: "Oportunidade", traduction: "Opportunité" },
      { mot: "Decisão", traduction: "Décision" },
      { mot: "Desenvolvimento", traduction: "Développement" },
      { mot: "Ambiente", traduction: "Environnement" },
      { mot: "Sociedade", traduction: "Société" },
      { mot: "Comparar", traduction: "Comparer" },
      { mot: "Explicar", traduction: "Expliquer" },
      { mot: "Sugerir", traduction: "Suggérer" },
      { mot: "Resolver", traduction: "Résoudre" }
    ],
    B2: [
      { mot: "Consciência", traduction: "Conscience / Sensibilisation" },
      { mot: "Mudança", traduction: "Changement" },
      { mot: "Desafio", traduction: "Défi" },
      { mot: "Sustentável", traduction: "Durable" },
      { mot: "Incentivar", traduction: "Encourager" },
      { mot: "Enfatizar", traduction: "Souligner" },
      { mot: "Aprofundar", traduction: "Approfondir" },
      { mot: "Alcançar", traduction: "Atteindre" },
      { mot: "Gerenciar", traduction: "Gérer" },
      { mot: "Evitar", traduction: "Éviter" }
    ],
    C1: [
      { mot: "Inelutável", traduction: "Inéluctable" },
      { mot: "Polêmica", traduction: "Polémique" },
      { mot: "Paradigma", traduction: "Paradigme" },
      { mot: "Heterogêneo", traduction: "Hétérogène" },
      { mot: "Distinguir", traduction: "Distinguer / Caractériser" },
      { mot: "Implementação", traduction: "Mise en œuvre" },
      { mot: "Reivindicar", traduction: "Revendiquer" },
      { mot: "Auspício", traduction: "Souhait" },
      { mot: "Delinear", traduction: "Esquisser / Tracer" },
      { mot: "Deter-se", traduction: "S'attarder" }
    ]
  },
  turc: {
    A1: [
      { mot: "Merhaba", traduction: "Bonjour" },
      { mot: "Teşekkür ederim", traduction: "Merci" },
      { mot: "Lütfen", traduction: "S'il vous plaît" },
      { mot: "Evet", traduction: "Oui" },
      { mot: "Hayır", traduction: "Non" },
      { mot: "Su", traduction: "Eau" },
      { mot: "Ekmek", traduction: "Pain" },
      { mot: "Yemek", traduction: "Manger / Repas" },
      { mot: "İçmek", traduction: "Boire" },
      { mot: "Uyku", traduction: "Sommeil / Dormir" },
      { mot: "Arkadaş", traduction: "Ami" },
      { mot: "Aile", traduction: "Famille" },
      { mot: "Ev", traduction: "Maison" },
      { mot: "Kitap", traduction: "Livre" },
      { mot: "Şehir", traduction: "Ville" },
      { mot: "Okul", traduction: "École" },
      { mot: "Araba", traduction: "Voiture" },
      { mot: "Zaman", traduction: "Temps" },
      { mot: "Güneş", traduction: "Soleil" },
      { mot: "Ay", traduction: "Lune" },
      { mot: "Deniz", traduction: "Mer" },
      { mot: "Dağ", traduction: "Montagne" },
      { mot: "Kırmızı", traduction: "Rouge" },
      { mot: "Mavi", traduction: "Bleu" },
      { mot: "Yeşil", traduction: "Vert" },
      { mot: "Bir", traduction: "Un" },
      { mot: "İki", traduction: "Deux" },
      { mot: "Üç", traduction: "Trois" },
      { mot: "Hoşça kal", traduction: "Au revoir" },
      { mot: "Rica ederim", traduction: "De rien" }
    ],
    A2: [
      { mot: "Seyahat", traduction: "Voyage" },
      { mot: "Yemek pişirmek", traduction: "Cuisiner" },
      { mot: "İş", traduction: "Travail" },
      { mot: "Sağlık", traduction: "Santé" },
      { mot: "Boş zaman", traduction: "Temps libre" },
      { mot: "Aramak", traduction: "Chercher" },
      { mot: "Bulmak", traduction: "Trouver" },
      { mot: "Anlamak", traduction: "Comprendre" },
      { mot: "Temizlemek", traduction: "Nettoyer" },
      { mot: "Satın almak", traduction: "Acheter" }
    ],
    B1: [
      { mot: "Deneyim", traduction: "Expérience" },
      { mot: "Fırsat", traduction: "Opportunité" },
      { mot: "Karar", traduction: "Décision" },
      { mot: "Gelişim", traduction: "Développement" },
      { mot: "Çevre", traduction: "Environnement" },
      { mot: "Toplum", traduction: "Société" },
      { mot: "Karşılaştırmak", traduction: "Comparer" },
      { mot: "Açıklamak", traduction: "Expliquer" },
      { mot: "Önermek", traduction: "Suggérer" },
      { mot: "Çözmek", traduction: "Résoudre" }
    ],
    B2: [
      { mot: "Farkındalık", traduction: "Conscience / Sensibilisation" },
      { mot: "Değişim", traduction: "Changement" },
      { mot: "Mücadele", traduction: "Défi" },
      { mot: "Sürdürülebilir", traduction: "Durable" },
      { mot: "Teşvik etmek", traduction: "Encourager" },
      { mot: "Vurgulamak", traduction: "Souligner" },
      { mot: "Derinleştirmek", traduction: "Approfondir" },
      { mot: "Ulaşmak", traduction: "Atteindre" },
      { mot: "Yönetmek", traduction: "Gérer" },
      { mot: "Kaçınmak", traduction: "Éviter" }
    ],
    C1: [
      { mot: "Kaçınılmaz", traduction: "Inéluctable" },
      { mot: "Tartışma", traduction: "Polémique" },
      { mot: "Paradigma", traduction: "Paradigme" },
      { mot: "Heterojen", traduction: "Hétérogène" },
      { mot: "Ayırt etmek", traduction: "Distinguer / Caractériser" },
      { mot: "Uygulama", traduction: "Mise en œuvre" },
      { mot: "Hak iddia etmek", traduction: "Revendiquer" },
      { mot: "Temenni", traduction: "Souhait" },
      { mot: "Anahatlarını çizmek", traduction: "Esquisser / Tracer" },
      { mot: "Üzerinde durmak", traduction: "S'attarder" }
    ]
  },
  espagnol: {
    A1: [
      { mot: "Hola", traduction: "Bonjour / Salut" },
      { mot: "Gracias", traduction: "Merci" },
      { mot: "Por favor", traduction: "S'il vous plaît" },
      { mot: "Sí", traduction: "Oui" },
      { mot: "No", traduction: "Non" },
      { mot: "Agua", traduction: "Eau" },
      { mot: "Pan", traduction: "Pain" },
      { mot: "Comer", traduction: "Manger" },
      { mot: "Beber", traduction: "Boire" },
      { mot: "Dormir", traduction: "Dormir" },
      { mot: "Amigo", traduction: "Ami" },
      { mot: "Familia", traduction: "Famille" },
      { mot: "Casa", traduction: "Maison" },
      { mot: "Libro", traduction: "Livre" },
      { mot: "Ciudad", traduction: "Ville" },
      { mot: "Escuela", traduction: "École" },
      { mot: "Coche", traduction: "Voiture" },
      { mot: "Tiempo", traduction: "Temps" },
      { mot: "Sol", traduction: "Soleil" },
      { mot: "Luna", traduction: "Lune" },
      { mot: "Mar", traduction: "Mer" },
      { mot: "Montaña", traduction: "Montagne" },
      { mot: "Rojo", traduction: "Rouge" },
      { mot: "Azul", traduction: "Bleu" },
      { mot: "Verde", traduction: "Vert" },
      { mot: "Uno", traduction: "Un" },
      { mot: "Dos", traduction: "Deux" },
      { mot: "Tres", traduction: "Trois" },
      { mot: "Adiós", traduction: "Au revoir" },
      { mot: "De nada", traduction: "De rien" }
    ],
    A2: [
      { mot: "Viaje", traduction: "Voyage" },
      { mot: "Cocinar", traduction: "Cuisiner" },
      { mot: "Trabajo", traduction: "Travail" },
      { mot: "Salud", traduction: "Santé" },
      { mot: "Tiempo libre", traduction: "Temps libre" },
      { mot: "Buscar", traduction: "Chercher" },
      { mot: "Encontrar", traduction: "Trouver" },
      { mot: "Entender", traduction: "Comprendre" },
      { mot: "Limpiar", traduction: "Nettoyer" },
      { mot: "Comprar", traduction: "Acheter" }
    ],
    B1: [
      { mot: "Experiencia", traduction: "Expérience" },
      { mot: "Oportunidad", traduction: "Opportunité" },
      { mot: "Decisión", traduction: "Décision" },
      { mot: "Desarrollo", traduction: "Développement" },
      { mot: "Medio ambiente", traduction: "Environnement" },
      { mot: "Sociedad", traduction: "Société" },
      { mot: "Comparar", traduction: "Comparer" },
      { mot: "Explicar", traduction: "Expliquer" },
      { mot: "Sugerir", traduction: "Suggérer" },
      { mot: "Resolver", traduction: "Résoudre" }
    ],
    B2: [
      { mot: "Conciencia", traduction: "Conscience / Sensibilisation" },
      { mot: "Cambio", traduction: "Changement" },
      { mot: "Desafío", traduction: "Défi" },
      { mot: "Sostenible", traduction: "Durable" },
      { mot: "Fomentar", traduction: "Encourager" },
      { mot: "Destacar", traduction: "Souligner" },
      { mot: "Profundizar", traduction: "Approfondir" },
      { mot: "Alcanzar", traduction: "Atteindre" },
      { mot: "Gestionar", traduction: "Gérer" },
      { mot: "Evitar", traduction: "Éviter" }
    ],
    C1: [
      { mot: "Ineludible", traduction: "Inéluctable" },
      { mot: "Polémica", traduction: "Polémique" },
      { mot: "Paradigma", traduction: "Paradigme" },
      { mot: "Heterogéneo", traduction: "Hétérogène" },
      { mot: "Caracterizar", traduction: "Distinguer / Caractériser" },
      { mot: "Implementación", traduction: "Mise en œuvre" },
      { mot: "Reivindicar", traduction: "Revendiquer" },
      { mot: "Auspicio", traduction: "Souhait" },
      { mot: "Delinear", traduction: "Esquisser / Tracer" },
      { mot: "Detenerse", traduction: "S'attarder" }
    ]
  }
};
